name: Tapmad Fancode Update

on:

  workflow_dispatch:

  schedule:
    - cron: "0 */6 * * *"


jobs:

  update-playlist:

    runs-on: ubuntu-latest


    env:

      TAPMAD_URL: ${{ secrets.TAPMAD_URL }}

      FANCODE_URL: ${{ secrets.FANCODE_URL }}


    steps:


      - name: Checkout repo
        uses: actions/checkout@v4



      - name: Setup Python
        uses: actions/setup-python@v5

        with:

          python-version: "3.11"



      - name: Install requirements
        run: |
          pip install requests



      - name: Update playlist
        run: |
          python Script/tap_fan.py



      - name: Commit changes
        run: |

          git config user.name "github-actions"

          git config user.email "github-actions@github.com"


          git add "Set on tv.m3u"


          git diff --cached --quiet || git commit -m "Update Tapmad Fancode channels"


          git push
